# Generated by Django 3.2.9 on 2023-06-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shteti',
            options={'verbose_name_plural': '6. Shteti'},
        ),
    ]
