# Generated by Django 3.2.9 on 2023-06-30 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shteti_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='shteti',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main.shteti'),
            preserve_default=False,
        ),
    ]
